name: Flutter App CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - developer

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.base_ref == 'developer')

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'

      - name: Increase version number
        run: |
          echo '#!/bin/bash' > bump_version.sh
          echo 'increment_build_number() {' >> bump_version.sh
          echo '  local version_line=$(grep "^version:" pubspec.yaml)' >> bump_version.sh
          echo '  local version=$(echo "$version_line" | awk '\''{print $2}'\'')' >> bump_version.sh
          echo '  local build_number=$(echo "$version" | cut -d '\''+'\'' -f2)' >> bump_version.sh
          echo '  local new_build_number=$((build_number + 1))' >> bump_version.sh
          echo '  local new_version=$(echo "$version" | sed "s/+$build_number\$/+$new_build_number/")' >> bump_version.sh
          echo '  sed -i.bak "s/^version:.*/version: $new_version/" pubspec.yaml' >> bump_version.sh
          echo '  echo "Updated pubspec.yaml to version $new_version"' >> bump_version.sh
          echo '}' >> bump_version.sh
          echo 'increment_build_number' >> bump_version.sh
          chmod +x bump_version.sh
          ./bump_version.sh

      - name: Install dependencies
        run: flutter pub get

      - name: Cache Flutter build
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Build APK
        run: flutter build apk --debug

      - name: List APK outputs
        run: ls build/app/outputs/flutter-apk

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Testers
          file: build/app/outputs/flutter-apk/app-debug.apk
